### ISSUE TITLE
"getFormValues" fails if Prototype 1.7 is used

### ISSUE THREAD

**Issue by lmazuel** [n1k0/casperjs#1212]
Hi,

I have a form which contains an empty select with no options, and options is an instance of HTMLOptionsCollection
```js
input
<select id="select_0incident.watch_list" style="direction:ltr; ;" onchange="toggleGlideListIcons('incident.watch_list', false);" name="select_0incident.watch_list" multiple="yes" fixedwidth="" size="6"></select>
input.options
[]
input.options.toString()
"[object HTMLOptionsCollection]"
```

When I tried to use `getFormValues`, it fails:
```js
#    error: callUtils(getFormValues) with args form[id$=do] thrown an error: 'undefined' is not a function (evaluating 'this.each(function(A,z){if(y.call(x,A,z)){w.push(A)}})')
#           CasperError: callUtils(getFormValues) with args form[id$=do] thrown an error: 'undefined' is not a function (evaluating 'this.each(function(A,z){if(y.call(x,A,z)){w.push(A)}})')
```

I have investigated a little, and found that the problem is in `clientutils.getFieldValue`, more precisely here:
```js
 if (input.type === 'select-multiple') {
                    return [].filter.call(input.options, function(option) {
                        return !!option.selected;
                    }).map(function(option) {
                        return option.value;
                    });
                }
```

The `filter` call does not works on HTMLOptionsCollection (Chrome 41.0.2272.118):
```js
> [].filter.call(input.options, function(option) {})
Uncaught TypeError: undefined is not a function
```

In my situation, adding a simple
```js
if(input.options.length == 0) {return []}
```
is enough (I'm not smart enough in Javascript to do a PR for the generic situation where options is not empty, sorry).

Tested with the lasted CapserJS from github (SHA1 e67dae78219831ddc0ab4fb81446eeb7968b01c8)

**Comment by paazmaya** [comment]
Would you like to add the suggested fix via pull request, tests included?

**Comment by lmazuel** [comment]
Hi,

Thank you for your answer. I have investigated more to find the problem. The problem isn't in CasperJS.
The Website I try to test with CasperJS use the Prototype (1.7) library, which redefines `Array.prototype.filter` using a new function `Array.prototype.each`. But they forget to add the `each` function to `HTMLOptionsCollection`. Then, using `filter` on `HTMLOptionsCollection` fails to `undefined is not a function`....

I think it's relative to this bug in Prototype https://github.com/sstephenson/prototype/issues/293

So, I will keep my ugly patch, since there is no reason to modify something in CasperJS and it's impossible for me to update the Prototype version on the website I test....

**Comment by lmazuel** [comment]
I confirm my fears, all works fine with Prototype 1.7.2.

Sorry for my bug report, I hope that it might help someone which will arrived here using Google...
